# Site settings
title: Afio
# header-img: img/home-bg.jpg
email: afio.iam#gmail.com
description: > # In case of memories fade away
baseurl: ""
url: "http://afio.im/"
twitter_username: afios
github_username:  afio
facebook_username:  iamafio

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: pretty
paginate: 100
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
